import { generateId, getDb, schema } from "@web3-hunter/db";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { getEnv } from "./env";

function createAuth() {
  const env = getEnv();

  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: drizzleAdapter(getDb(), {
      provider: "pg",
      schema: {
        user: schema.user,
        session: schema.session,
        account: schema.account,
        verification: schema.verification,
      },
    }),
    emailAndPassword: {
      enabled: true,
    },
    advanced: {
      database: {
        // Every ID in this system is a UUIDv7 generated by
        // @web3-hunter/db's own generateId (docs/DATABASE.md §4) — a
        // Company, an Opportunity, a Skill, all of it. Better Auth's
        // default ID generator produces a plain random alphanumeric
        // string, not a UUID, which is incompatible with the canonical
        // Event envelope's `relatedEntityId` (a `uuid` column, validated
        // as UUID-shaped by packages/events' eventEnvelopeSchema) — an
        // Event referencing a User (e.g. `MatchComputed`) would fail to
        // publish otherwise. Reusing the same generator keeps every ID in
        // the system one consistent, sortable shape.
        generateId: () => generateId(),
      },
    },
  });
}

type Auth = ReturnType<typeof createAuth>;

let instance: Auth | undefined;

/**
 * Returns the shared Better Auth server instance, constructed lazily on
 * first use for the same reason as `@web3-hunter/db`'s `getDb`: importing
 * this module (e.g. while Next.js collects routes at build time) must never
 * require a live database or a configured secret — only handling a real
 * request should.
 *
 * Explicitly wired to `@web3-hunter/db`'s `user`/`session`/`account`/
 * `verification` tables (docs/ROADMAP.md Milestone 5) — Milestone 0 wired
 * this code path but never gave Better Auth its own real, migrated schema.
 */
export function getAuth(): Auth {
  instance ??= createAuth();
  return instance;
}
